fix: create release action when there is no previous tag
pbstck/actions pull request #22
Opened 2022-11-18 15:33 UTC by ridwan-b

If there is no previous tag, then the pipeline failed because of an undefined property.
This PR is to fix this.

2022-11-20 14:28 UTC, cforycki reviewed
Which version of node did you use to compile?
Having that much diff in the generated code is a bit weird so I tried to compile it myself and I don't have the same output as you.

2022-11-20 14:28 UTC, cforycki commented on create-release/index.js
> +    let previousTagName = previousTag ? previousTag.name : "No previous tag";
```suggestion
    const previousTagName = previousTag ? previousTag.name : "No previous tag";
```

By the way, is this really working? 
I can't find mention of `"No previous tag"` in the [github api doc](https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release)

2022-11-21 08:41 UTC, ridwan-b commented on create-release/index.js
> +    let previousTagName = previousTag ? previousTag.name : "No previous tag";
Actually, I thought it was a declarative field where I could put anything.
I should have read the doc before, it seems that if there is not previous tag, we have to let it empty. I'll change this

2022-11-21 09:30 UTC, ridwan-b commented
This new version has been successfully tested on kleanad-prebid [](https://github.com/pbstck/kleanads-prebid/releases)

2022-11-24 13:44 UTC, cforycki requested changes

2022-11-24 13:44 UTC, cforycki commented on create-release/index.js
> +    let dataReleaseNoteGenerated = {
```suggestion
    const dataReleaseNoteGenerated = {
```

2022-11-24 13:44 UTC, cforycki commented on create-release/index.js
> +        console.log('Previous tag', previousTag?.name)
No need for optional chaining here, you already check the variable in the if condition.
```suggestion
        dataReleaseNoteGenerated.previous_tag_name = previousTag.name;
        console.log('Previous tag', previousTag.name)
```

2022-11-24 15:59 UTC, cforycki approved these changes

2022-11-24 17:00 UTC, slezier approved these changes

2022-11-25 08:19 UTC, lestrade-pbstck approved these changes

2022-11-25 13:08 UTC, ildede approved these changes

2022-11-25 13:16 UTC, vmaerten approved these changes

2022-11-28 09:57 UTC, afigoureux-pbstck approved these changes

2022-11-28 16:11 UTC, merged